name: 问题反馈
description: 提交你遇到的问题，帮助开发者了解和修复
labels: []
body:
  - type: markdown
    attributes:
      value: |
        感谢您花费时间填写此问题反馈!
        请尽可能提供有效的信息帮助我更好地理解您遇到的问题。

  - type: checkboxes
    id: checklist
    attributes:
      label: Issue Checklist
      description: |
        在提交问题之前，请确保您已完成以下步骤
      options:
        - label: 我在[Open Issues](https://github.com/teojs/clock-dashboard/issues)和[Closed Issues](https://github.com/teojs/clock-dashboard/issues?q=is%3Aissue%20state%3Aclosed)中搜索过，没有找到类似的问题。
          required: true

  - type: dropdown
    id: platform
    attributes:
      label: 你所使用的设备平台
      description: 请选择你使用的设备平台信息
      options:
        - iOS
        - Android
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 系统版本
      description: 请输入你使用的系统版本信息
      placeholder: e.g. Windows 10、iOS 14.0、Android 10.0
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: 浏览器版本
      description: 请输入你使用的浏览器版本信息
      placeholder: e.g. Chrome 120、Safari 12.5.0
    validations:
      required: true

  - type: input
    id: resolution
    attributes:
      label: 分辨率
      description: 请输入你使用的分辨率信息
      placeholder: e.g. 1920*1080、2560*1440
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 你遇到了什么问题
      description: 请尽可能详细地描述你遇到的问题。请提供截图或录屏，帮助我们更好地理解问题。
      placeholder: 告诉我发生了什么... (如果可能的话，请提供截图或录屏)
    validations:
      required: true
